[advisories]
version = 2
yanked = "warn"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[licenses]
confidence-threshold = 0.9
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
