[package]
name = "incur"
description = "A typed CLI framework for agents and humans"
keywords = ["ai", "agent", "cli", "mcp", "schema"]
categories = ["command-line-interface", "development-tools"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "../README.md"
exclude = ["tests/fixtures"]

[features]
default = ["completions", "http", "mcp", "skills", "tokens", "toon", "yaml"]
completions = ["dep:clap_complete"]
http = ["dep:form_urlencoded", "dep:http", "dep:percent-encoding"]
mcp = ["dep:toml_edit"]
skills = ["dep:sha2"]
tokens = ["dep:tiktoken-rs"]
toon = ["dep:toon-format"]
yaml = ["dep:serde_yaml"]

[dependencies]
clap.workspace = true
clap_derive.workspace = true
clap_complete = { workspace = true, optional = true }
eyre.workspace = true
form_urlencoded = { workspace = true, optional = true }
http = { workspace = true, optional = true }
incur-macros = { path = "../incur-macros", version = "0.1.0" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
thiserror.workspace = true
tiktoken-rs = { workspace = true, optional = true }
tokio.workspace = true
toml_edit = { workspace = true, optional = true }
toon-format = { workspace = true, optional = true }
percent-encoding = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
